#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Merge Claude-extracted candidate rows into the factlog KB.

Input contract:
    Claude writes extracted fact rows as JSON (FACT_HEADER schema) under
    $FACTLOG_ROOT/runs/*.json.  This script reads those files, normalises and
    deduplicates the rows, then writes:

        facts/candidates.csv
        pages/<entity>.md
        decisions/open-questions.md   (needs_review bullets)
        decisions/open-questions.md   (stale source refs)

    Finally it delegates structural validation to tools/validate.py.

Canonical source value:
    The "source" field in each candidate row MUST be a path relative to the
    KB root, prefixed with "sources/".  Examples:
        "sources/my-doc.md"
        "sources/subdir/notes.md#section-heading"
    Bare filenames (e.g. "my-doc.md") are NOT valid.  The extraction step in
    the factlog skill must emit fully-qualified sources/-prefixed paths.

What this script does NOT do:
    - parallel worker fan-out or subprocess CLI plumbing (native Claude session)
    - parse_claude_rows / build_source_prompt (LLM steps stay in the skill)
    - SyncReport / print_sync_report (subprocess orchestration)

Usage:
    python3 tools/merge_candidates.py --wiki /path/to/kb

    --wiki      KB root (overrides FACTLOG_ROOT; this flag is authoritative and
                does NOT require FACTLOG_ROOT to be set in the environment).
    --input     Glob pattern relative to KB root for input JSON files.
                Default: runs/*.json  (sourced from common.RUNS_DIR)
    --strict    Exit non-zero if any input row is rejected during normalisation
                (useful in automation to surface contract violations).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Pre-pass: resolve --wiki BEFORE importing common.py so the module-level
# ROOT global captures the correct KB root regardless of the caller's cwd or
# whether FACTLOG_ROOT is set in the environment.
# ---------------------------------------------------------------------------

import argparse
import os
import sys
from pathlib import Path

# Ensure the tools/ directory is on sys.path when this script is run
# directly (python3 tools/merge_candidates.py) so common can be imported.
_TOOLS_DIR = Path(__file__).parent
if str(_TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(_TOOLS_DIR))


def _resolve_wiki_prepass() -> str:
    """Parse --wiki from argv without consuming it (for env setup only)."""
    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument("--wiki", default=None)
    known, _ = pre.parse_known_args()
    if known.wiki:
        return str(Path(known.wiki).expanduser().resolve())
    # Fall back to FACTLOG_ROOT or cwd
    return str(Path(os.environ.get("FACTLOG_ROOT", ".")).expanduser().resolve())


# Set FACTLOG_ROOT *before* importing common so the module-level ROOT is correct.
os.environ["FACTLOG_ROOT"] = _resolve_wiki_prepass()

# ---------------------------------------------------------------------------
# Now it is safe to import common (ROOT is already set correctly above).
# ---------------------------------------------------------------------------

import csv  # noqa: E402
import json  # noqa: E402
import re  # noqa: E402
import subprocess  # noqa: E402
from datetime import datetime, timezone  # noqa: E402

from common import (  # noqa: E402
    FACT_HEADER,
    ENGINE_STATUSES,
    REVIEW_STATUSES,
    SUPERSEDED_STATUSES,
    RUNS_DIR,
    ensure_dirs,
    normalize_confidence,
    slugify,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Combined set of statuses that are valid in candidates.csv.
# run_fact_sync.py used {confirmed, needs_review}; factlog common.py defines
# ENGINE_STATUSES={confirmed, accepted} and REVIEW_STATUSES={needs_review,
# candidate}.  We accept all four so that rows produced by either the old
# llmwiki-ops worker or the new native Claude extraction are preserved.
VALID_STATUSES: frozenset[str] = frozenset(ENGINE_STATUSES | REVIEW_STATUSES | SUPERSEDED_STATUSES)

# Marker written into auto-generated concept pages.
# We use a factlog-specific marker ("generated-by-factlog") so that pages
# previously generated by earlier tooling (e.g. pages carrying a different
# marker from a prior migration run) are NOT reclaimed — they remain intact
# and this script only manages pages it has itself created.
GENERATED_PAGE_MARKER = "<!-- generated-by-factlog -->"


# ---------------------------------------------------------------------------
# Source-file helpers
# ---------------------------------------------------------------------------

# A KB has two source roots: sources/ (the user's originals) and runs/sources/
# (text conversions of binary originals produced by `factlog ingest`). Both are
# valid `source` locations for extracted facts.
SOURCE_ROOTS = ("sources", "runs/sources")


def source_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for rel in SOURCE_ROOTS:
        base = root / rel
        if base.is_dir():
            files.extend(path for path in base.rglob("*") if path.is_file())
    return sorted(files)


def source_file_refs(root: Path) -> set[str]:
    """Return source paths relative to the KB root (sources/- or runs/sources/-prefixed).

    Example: <root>/sources/my-doc.md -> 'sources/my-doc.md';
             <root>/runs/sources/report.md -> 'runs/sources/report.md'.
    These paths match the canonical source value that candidate rows must use.
    """
    return {path.relative_to(root).as_posix() for path in source_files(root)}


def is_text_source(path: Path, *, sniff: int = 8192) -> bool:
    """Return True iff *path*'s leading bytes look like readable UTF-8 text.

    The in-session fact extraction reads each sources/ file as text, so a file is
    only ingestible if it decodes as text. A file is treated as non-text when its
    first *sniff* bytes contain a NUL byte or do not decode as UTF-8 (tolerating a
    multi-byte sequence truncated at the sniff boundary). Detection is
    content-based, so binary formats (.docx, .pdf, images, ...) are flagged
    regardless of their extension.
    """
    try:
        chunk = path.read_bytes()[:sniff]
    except OSError:
        return False
    if b"\x00" in chunk:
        return False
    try:
        chunk.decode("utf-8")
    except UnicodeDecodeError as exc:
        # A multi-byte UTF-8 char may be cut at the sniff boundary; tolerate it.
        return exc.start >= len(chunk) - 3
    return True


def unconverted_binary_sources(root: Path) -> list[str]:
    """List binary files under sources/ that have no runs/sources/ conversion.

    A binary original in sources/ yields no facts on its own, but if
    `factlog ingest` has produced a runs/sources/<stem>.{md,txt} conversion the
    text IS ingested, so such originals are NOT reported. Hidden/system files
    (names starting with '.', e.g. .DS_Store) are skipped to avoid noise.
    """
    base = root / "sources"
    derived = root / "runs" / "sources"
    if not base.is_dir():
        return []
    found: list[str] = []
    for path in sorted(p for p in base.rglob("*") if p.is_file()):
        if path.name.startswith("."):
            continue
        if is_text_source(path):
            continue
        if any((derived / f"{path.stem}{ext}").is_file() for ext in (".md", ".txt")):
            continue
        found.append(path.relative_to(root).as_posix())
    return found


# ---------------------------------------------------------------------------
# Input: read candidate rows from runs/*.json
# ---------------------------------------------------------------------------

def load_candidate_files(root: Path, pattern: str = "runs/*.json") -> list[dict[str, str]]:
    """Read all JSON files matching *pattern* under *root*.

    Each file must contain a JSON array of objects with FACT_HEADER keys.
    Invalid rows are skipped with a warning; invalid files raise SystemExit.

    The "source" field in each row must be a sources/-prefixed path relative to
    the KB root (e.g. "sources/my-doc.md").  Bare filenames are NOT accepted.
    """
    rows: list[dict[str, str]] = []
    candidate_files = sorted(root.glob(pattern))
    if not candidate_files:
        # No candidates yet — not an error; we will just write an empty CSV.
        return rows

    for path in candidate_files:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            raise SystemExit(f"failed to parse {path.relative_to(root)}: {exc}") from exc
        if not isinstance(data, list):
            # Not a candidate-rows file (a fact run is a JSON array). Other tools
            # also write JSON under runs/ — e.g. generate_logic_policy.py writes
            # runs/natural-language-to-policy-response.json (an object). Skip such
            # non-array files with a warning instead of failing, so the pipeline
            # stays idempotent when those artifacts are present.
            print(
                f"  skip non-candidate JSON in {path.parent.name}/: {path.name} (not a JSON array)",
                file=sys.stderr,
            )
            continue
        for item in data:
            if not isinstance(item, dict):
                continue
            row = {field: str(item.get(field, "")).strip() for field in FACT_HEADER}
            if all(row[field] for field in FACT_HEADER[:4]):
                rows.append(row)
            else:
                print(
                    f"  skip incomplete row in {path.name}: {item}",
                    file=sys.stderr,
                )
    return rows


# ---------------------------------------------------------------------------
# Normalise & dedup
# ---------------------------------------------------------------------------

def normalize_rows(
    root: Path,
    rows: list[dict[str, str]],
    *,
    strict: bool = False,
) -> list[dict[str, str]]:
    """Validate, normalise, and deduplicate raw candidate rows.

    The "source" field must be a sources/-prefixed path relative to the KB root
    (e.g. "sources/my-doc.md" or "sources/subdir/notes.md#anchor").  A bare
    filename ("my-doc.md") does not match and the row is dropped.

    - status is normalised to 'needs_review' if not in VALID_STATUSES
    - confidence is clamped to [0.00, 1.00]
    - exact duplicate (subject, relation, object, source) tuples are dropped
    - result is sorted by (source, subject, relation, object)

    If *strict* is True, any dropped row causes a non-zero exit.
    """
    known_sources = source_file_refs(root)
    seen: set[tuple[str, str, str, str]] = set()
    normalized: list[dict[str, str]] = []
    dropped = 0

    for row in rows:
        source = row["source"]
        # Compare the pre-anchor portion against known sources/-prefixed refs.
        # The canonical source value is already sources/-prefixed; bare filenames
        # will not match and are dropped with a warning.
        source_file = source.partition("#")[0]
        if source_file not in known_sources:
            print(
                f"  skip row: source '{source_file}' not found in sources/ "
                f"(expected a sources/- or runs/sources/-prefixed path like 'sources/{Path(source_file).name}')",
                file=sys.stderr,
            )
            dropped += 1
            if strict:
                raise SystemExit(
                    f"--strict: input row rejected (source not found): {source_file}"
                )
            continue
        clean = {field: row.get(field, "").strip() for field in FACT_HEADER}
        clean["status"] = clean["status"] if clean["status"] in VALID_STATUSES else "needs_review"
        clean["confidence"] = normalize_confidence(clean["confidence"])
        key = (clean["subject"], clean["relation"], clean["object"], clean["source"])
        if key in seen:
            dropped += 1
            continue
        seen.add(key)
        normalized.append(clean)

    if dropped:
        print(f"  warning: {dropped} row(s) dropped during normalise/dedup", file=sys.stderr)

    return sorted(
        normalized,
        key=lambda item: (item["source"], item["subject"], item["relation"], item["object"]),
    )


# ---------------------------------------------------------------------------
# Write facts/candidates.csv
# ---------------------------------------------------------------------------

def write_facts(root: Path, rows: list[dict[str, str]]) -> None:
    out = root / "facts" / "candidates.csv"
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FACT_HEADER)
        writer.writeheader()
        writer.writerows(rows)


# ---------------------------------------------------------------------------
# Write pages/<entity>.md
# ---------------------------------------------------------------------------

def page_filename(title: str) -> str:
    return f"{slugify(title)}.md"


def write_pages(root: Path, rows: list[dict[str, str]]) -> list[str]:
    """Generate per-entity concept pages from confirmed/accepted candidate rows.

    Only pages carrying GENERATED_PAGE_MARKER are touched; hand-authored pages
    are never overwritten.  Pre-existing pages generated by earlier tooling
    that carry a different marker are NOT reclaimed — they remain as-is and
    are excluded from this script's management scope.
    """
    pages_dir = root / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)

    # Remove previously generated pages (ours only).
    for page in pages_dir.glob("*.md"):
        text = page.read_text(encoding="utf-8", errors="ignore")
        if GENERATED_PAGE_MARKER in text:
            page.unlink()

    # Superseded rows are retired: keep them in candidates.csv (audit) but do not
    # render them on concept pages, where they would read as the current value.
    rows = [row for row in rows if row.get("status") not in SUPERSEDED_STATUSES]

    by_entity: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        by_entity.setdefault(row["subject"], []).append(row)
        by_entity.setdefault(row["object"], []).append(row)

    written: list[str] = []
    for entity, entity_rows in sorted(by_entity.items()):
        if not entity.strip():
            continue
        path = pages_dir / page_filename(entity)
        # Skip hand-authored pages that don't carry our marker.
        if path.exists() and GENERATED_PAGE_MARKER not in path.read_text(encoding="utf-8", errors="ignore"):
            continue

        source_lines = sorted({f"- {row['source']}" for row in entity_rows})
        relation_lines: list[str] = []
        review_lines: list[str] = []

        for row in entity_rows:
            if row["subject"] == entity:
                relation_lines.append(
                    f"- {row['relation']} -> [[{row['object']}]]"
                    f" ({row['source']}, confidence={row['confidence']})"
                )
            else:
                relation_lines.append(
                    f"- [[{row['subject']}]] -> {row['relation']}"
                    f" ({row['source']}, confidence={row['confidence']})"
                )
            if row["status"] in REVIEW_STATUSES:
                review_lines.append(
                    f"- {row['subject']} / {row['relation']} / {row['object']}"
                    f" (confidence={row['confidence']}): {row['note']}"
                )

        text = "\n".join(
            [
                GENERATED_PAGE_MARKER,
                f"# {entity}",
                "",
                "## 요약",
                "- `sources/`에서 추출된 candidate fact를 기준으로 정리한 개념입니다.",
                "",
                "## 출처",
                *(source_lines or ["- 확인된 source가 없습니다."]),
                "",
                "## 관련 페이지",
                *(relation_lines or ["- 확인된 관계가 없습니다."]),
                "",
                "## 확인 필요",
                *(review_lines or ["- 현재 추출 결과에서 별도 검토 항목이 없습니다."]),
                "",
            ]
        )
        path.write_text(text, encoding="utf-8")
        written.append(path.relative_to(root).as_posix())

    return written


# ---------------------------------------------------------------------------
# Write decisions/open-questions.md
# ---------------------------------------------------------------------------

def decision_section(row: dict[str, str]) -> str:
    text = " ".join(row.get(key, "") for key in ["subject", "relation", "object", "note"]).lower()
    if any(word in text for word in ["duplicate", "same_concept", "same_as", "동일", "중복"]):
        return "## 중복 개념 후보"
    if any(word in text for word in ["source", "evidence", "출처"]):
        return "## 출처 부족"
    if any(word in text for word in ["conflict", "충돌"]):
        return "## 기존 내용과 충돌할 수 있는 항목"
    return "## 모호한 관계명"


def insert_bullet(text: str, section: str, bullet: str) -> str:
    if bullet in text:
        return text
    lines = text.splitlines()
    try:
        index = lines.index(section)
    except ValueError:
        if text and not text.endswith("\n"):
            text += "\n"
        return f"{text}\n{section}\n{bullet}\n"

    insert_at = index + 1
    while insert_at < len(lines) and not lines[insert_at].startswith("## "):
        insert_at += 1
    if insert_at > index + 1 and lines[insert_at - 1].strip():
        lines.insert(insert_at, "")
        insert_at += 1
    lines.insert(insert_at, bullet)
    return "\n".join(lines).rstrip() + "\n"


def write_decisions(root: Path, rows: list[dict[str, str]]) -> list[str]:
    decisions = root / "decisions" / "open-questions.md"
    decisions.parent.mkdir(parents=True, exist_ok=True)
    text = decisions.read_text(encoding="utf-8") if decisions.exists() else "# Open Questions\n"
    added: list[str] = []
    for row in rows:
        if row["status"] not in REVIEW_STATUSES:
            continue
        bullet = (
            f"- needs_review: {row['subject']} / {row['relation']} / "
            f"{row['object']} ({row['source']}, confidence={row['confidence']}) - {row['note']}"
        )
        before = text
        text = insert_bullet(text, decision_section(row), bullet)
        if text != before:
            added.append(bullet)
    decisions.write_text(text, encoding="utf-8")
    return added


# ---------------------------------------------------------------------------
# Record stale page references
# ---------------------------------------------------------------------------

def existing_source_refs(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    return re.findall(r"sources/[^\s`)>,]+?\.md(?:#[^\s`)>,]+)?", text)


def record_stale_page_refs(root: Path) -> list[str]:
    known_sources = source_file_refs(root)
    decisions = root / "decisions" / "open-questions.md"
    text = decisions.read_text(encoding="utf-8") if decisions.exists() else "# Open Questions\n"
    added: list[str] = []
    for page in sorted((root / "pages").glob("*.md")):
        for ref in existing_source_refs(page):
            source_file = ref.partition("#")[0]
            if source_file in known_sources:
                continue
            bullet = f"- stale_source: {page.relative_to(root).as_posix()} references removed source {ref}"
            before = text
            text = insert_bullet(text, "## 출처 부족", bullet)
            if text != before:
                added.append(bullet)
    decisions.write_text(text, encoding="utf-8")
    return added


# ---------------------------------------------------------------------------
# Validation delegate — repoints to tools/validate.py (u5)
# ---------------------------------------------------------------------------

def validate_outputs(root: Path) -> int:
    """Delegate structural validation to tools/validate.py.

    This replaces the old run_fact_sync.py reference to validate_fact_sync.py.
    """
    validator = Path(__file__).parent / "validate.py"
    if not validator.is_file():
        print(f"warning: validate.py not found at {validator}", file=sys.stderr)
        return 0
    completed = subprocess.run(
        [sys.executable, str(validator), str(root)],
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.stdout.strip():
        print(completed.stdout.strip())
    if completed.stderr.strip():
        print(completed.stderr.strip(), file=sys.stderr)
    return completed.returncode


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def existing_superseded_keys(root: Path) -> set[tuple[str, str, str, str]]:
    """(subject, relation, object, source) of rows currently marked 'superseded'
    in candidates.csv. Preserved across re-merge so a human's conflict resolution
    sticks even when a run re-asserts the retired fact."""
    csv_path = root / "facts" / "candidates.csv"
    if not csv_path.is_file():
        return set()
    keys: set[tuple[str, str, str, str]] = set()
    with csv_path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if (row.get("status") or "").strip() in SUPERSEDED_STATUSES:
                keys.add(
                    (
                        (row.get("subject") or "").strip(),
                        (row.get("relation") or "").strip(),
                        (row.get("object") or "").strip(),
                        (row.get("source") or "").strip(),
                    )
                )
    return keys


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Merge Claude-extracted candidate rows (runs/*.json) into the factlog KB.\n"
            "\n"
            "Input: JSON files under $FACTLOG_ROOT/runs/ produced by the native\n"
            "Claude fact-extraction step in the factlog skill.  Each file must\n"
            "contain a JSON array of objects with the FACT_HEADER schema:\n"
            "  [subject, relation, object, source, status, confidence, note]\n"
            "\n"
            "The 'source' field MUST be a sources/- or runs/sources/-prefixed path relative to the KB\n"
            "root (e.g. 'sources/my-doc.md').  Bare filenames are not accepted.\n"
            "\n"
            "Output: facts/candidates.csv, pages/, decisions/open-questions.md"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--wiki",
        default=os.environ.get("FACTLOG_ROOT", "."),
        help="KB root (authoritative; sets FACTLOG_ROOT; default: $FACTLOG_ROOT or '.')",
    )
    parser.add_argument(
        "--input",
        default=None,
        help=(
            "glob pattern relative to KB root for input JSON files "
            "(default: runs/*.json via common.RUNS_DIR)"
        ),
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="exit non-zero if any input row is rejected during normalisation",
    )
    args = parser.parse_args()

    root = Path(args.wiki).expanduser().resolve()

    # Derive the default --input glob from common.RUNS_DIR so the runs/ location
    # is single-sourced from common.py.
    if args.input is not None:
        input_pattern = args.input
    else:
        try:
            input_pattern = f"{RUNS_DIR.relative_to(root)}/*.json"
        except ValueError:
            input_pattern = "runs/*.json"

    # Validate KB structure and ensure output directories exist.
    ensure_dirs()

    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    print(f"merge_candidates run_id={run_id} wiki={root}")

    # ------------------------------------------------------------------
    # 0. Surface binary source files in sources/ that have NO runs/sources/
    # conversion. Extraction reads sources/ as text, so an un-ingested binary
    # yields no facts (silent non-ingestion). Warn always; under --strict treat
    # their presence as a hard failure.
    # ------------------------------------------------------------------
    nontext_sources = unconverted_binary_sources(root)
    if nontext_sources:
        print(
            f"  WARNING: {len(nontext_sources)} binary source file(s) in sources/ "
            "have no runs/sources/ conversion and will yield no facts "
            "(run `factlog ingest --scan` to convert them):",
            file=sys.stderr,
        )
        for name in nontext_sources:
            print(f"    - {name}", file=sys.stderr)

    # ------------------------------------------------------------------
    # 1. Read candidate rows from runs/*.json
    # ------------------------------------------------------------------
    raw_rows = load_candidate_files(root, input_pattern)
    print(f"  candidate rows loaded: {len(raw_rows)}")

    # ------------------------------------------------------------------
    # 2. Normalise and deduplicate
    # ------------------------------------------------------------------
    rows = normalize_rows(root, raw_rows, strict=args.strict)
    print(f"  rows after normalise/dedup: {len(rows)}")

    # Preserve human-marked supersessions across re-merge: a row previously set
    # to 'superseded' in candidates.csv stays superseded even if a run re-asserts
    # it — so a conflict resolution (see check_conflicts.py) is durable.
    superseded_keys = existing_superseded_keys(root)
    if superseded_keys:
        preserved = 0
        for row in rows:
            key = (row["subject"], row["relation"], row["object"], row["source"])
            if key in superseded_keys and row["status"] not in SUPERSEDED_STATUSES:
                row["status"] = "superseded"
                preserved += 1
        if preserved:
            print(f"  preserved {preserved} superseded row(s) from candidates.csv")

    # Warn prominently when rows were loaded but all were dropped — this
    # distinguishes a silent contract violation from a genuinely empty run.
    if raw_rows and not rows:
        print(
            "  WARNING: all candidate rows were dropped during normalise/dedup "
            "(0 rows survived).  Check that source values are sources/- or runs/sources/-prefixed paths.",
            file=sys.stderr,
        )
        if args.strict:
            return 1

    # ------------------------------------------------------------------
    # 3. Write facts/candidates.csv
    # ------------------------------------------------------------------
    write_facts(root, rows)
    print(f"  facts/candidates.csv written ({len(rows)} rows)")

    # ------------------------------------------------------------------
    # 4. Record stale page references (before pages are re-generated)
    # ------------------------------------------------------------------
    stale_refs_added = record_stale_page_refs(root)
    print(f"  stale page refs recorded: {len(stale_refs_added)}")

    # ------------------------------------------------------------------
    # 5. Write pages/<entity>.md
    # ------------------------------------------------------------------
    pages_written = write_pages(root, rows)
    print(f"  pages written: {len(pages_written)}")

    # ------------------------------------------------------------------
    # 6. Write decisions/open-questions.md bullets for needs_review rows
    # ------------------------------------------------------------------
    decisions_added = write_decisions(root, rows)
    print(f"  decision bullets added: {len(decisions_added)}")

    # ------------------------------------------------------------------
    # 7. Delegate structural validation to tools/validate.py
    # Validation is informational: merge_candidates exits 0 on success
    # regardless of validation result.  Callers that need strict validation
    # should run tools/validate.py directly.
    # ------------------------------------------------------------------
    validation_code = validate_outputs(root)
    if validation_code != 0:
        print(f"  validation warnings (exit {validation_code}) — run validate.py for details", file=sys.stderr)

    if args.strict and nontext_sources:
        print(
            f"--strict: {len(nontext_sources)} unconverted binary source file(s) in sources/",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
