#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Merge Claude-extracted candidate rows into the factlog KB.

Input contract:
    Claude writes extracted fact rows as JSON (FACT_HEADER schema) under
    $FACTLOG_ROOT/runs/*.json.  This script reads those files, normalises and
    deduplicates the rows, then writes:

        facts/candidates.csv
        pages/<entity>.md
        decisions/open-questions.md   (needs_review bullets)
        decisions/open-questions.md   (stale source refs)

    Finally it delegates structural validation to tools/validate.py.

Canonical source value:
    The "source" field in each candidate row MUST be a path relative to the
    KB root, prefixed with "sources/".  Examples:
        "sources/my-doc.md"
        "sources/subdir/notes.md#section-heading"
    Bare filenames (e.g. "my-doc.md") are NOT valid.  The extraction step in
    the factlog skill must emit fully-qualified sources/-prefixed paths.

What this script does NOT do:
    - parallel worker fan-out or subprocess CLI plumbing (native Claude session)
    - parse_claude_rows / build_source_prompt (LLM steps stay in the skill)
    - SyncReport / print_sync_report (subprocess orchestration)

Usage:
    python3 tools/merge_candidates.py --wiki /path/to/kb

    --wiki      KB root (overrides FACTLOG_ROOT; this flag is authoritative and
                does NOT require FACTLOG_ROOT to be set in the environment).
    --input     Glob pattern relative to KB root for input JSON files.
                Default: runs/*.json  (sourced from common.RUNS_DIR)
    --strict    Exit non-zero if any input row is rejected during normalisation
                (useful in automation to surface contract violations).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Pre-pass: resolve --wiki BEFORE importing common.py so the module-level
# ROOT global captures the correct KB root regardless of the caller's cwd or
# whether FACTLOG_ROOT is set in the environment.
# ---------------------------------------------------------------------------

import argparse
import os
import sys
from pathlib import Path

# Ensure the tools/ directory is on sys.path when this script is run
# directly (python3 tools/merge_candidates.py) so common can be imported.
_TOOLS_DIR = Path(__file__).parent
if str(_TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(_TOOLS_DIR))


# Resolve the KB root and export it before importing common, which binds
# its module-level paths from FACTLOG_ROOT at import time.
import factlog_config  # noqa: E402

os.environ["FACTLOG_ROOT"] = factlog_config.resolve_root_from_argv("--wiki")

# ---------------------------------------------------------------------------
# Now it is safe to import common (ROOT is already set correctly above).
# ---------------------------------------------------------------------------

import csv  # noqa: E402
import json  # noqa: E402
import re  # noqa: E402
import subprocess  # noqa: E402
import unicodedata  # noqa: E402
from datetime import datetime, timezone  # noqa: E402

from common import (  # noqa: E402
    FACT_HEADER,
    ENGINE_STATUSES,
    REVIEW_STATUSES,
    SUPERSEDED_STATUSES,
    RUNS_DIR,
    ensure_dirs,
    is_sync_ignored,
    is_text_source,
    normalize_confidence,
    slugify,
    source_file_refs,
    sync_ignore_patterns,
)
from factlog import literal_types  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Combined set of statuses that are valid in candidates.csv.
# run_fact_sync.py used {confirmed, needs_review}; factlog common.py defines
# ENGINE_STATUSES={confirmed, accepted} and REVIEW_STATUSES={needs_review,
# candidate}.  We accept all four so that rows produced by either the old
# llmwiki-ops worker or the new native Claude extraction are preserved.
VALID_STATUSES: frozenset[str] = frozenset(ENGINE_STATUSES | REVIEW_STATUSES | SUPERSEDED_STATUSES)

# Marker written into auto-generated concept pages.
# We use a factlog-specific marker ("generated-by-factlog") so that pages
# previously generated by earlier tooling (e.g. pages carrying a different
# marker from a prior migration run) are NOT reclaimed — they remain intact
# and this script only manages pages it has itself created.
GENERATED_PAGE_MARKER = "<!-- generated-by-factlog -->"

# Concept-page layout. A KB may override this by placing a template at
# <kb>/templates/pages.md (see load_page_template); absent that file, this
# built-in default is used so existing KBs keep their current page layout.
# Placeholders ({{ENTITY}}, {{SOURCES}}, {{RELATIONS}}, {{REVIEW}}) follow the
# same {{...}} convention as the policy/prompts templates.
#
# IMPORTANT: keep this byte-identical to factlog/cli.py _TEMPLATES["templates/
# pages.md"]; tests/test_page_template.sh pins the two to prevent divergence.
PAGE_TEMPLATE_REL = "templates/pages.md"
DEFAULT_PAGE_TEMPLATE = """\
<!-- generated-by-factlog -->
# {{ENTITY}}

## 요약
- `sources/`에서 추출된 candidate fact를 기준으로 정리한 개념입니다.

## 출처
{{SOURCES}}

## 관련 페이지
{{RELATIONS}}

## 확인 필요
{{REVIEW}}
"""

# Matches exactly the four supported page placeholders. Substitution is a single
# regex pass (see render_page) so a value injected into one slot can never be
# re-scanned and re-substituted as another slot's placeholder.
_PAGE_PLACEHOLDER_RE = re.compile(r"\{\{(ENTITY|SOURCES|RELATIONS|REVIEW)\}\}")


# ---------------------------------------------------------------------------
# Source-file helpers
# ---------------------------------------------------------------------------

# A KB has two source roots: sources/ (the user's originals) and runs/sources/
# (text conversions of binary originals produced by `factlog ingest`). Both are
# valid `source` locations for extracted facts. Source discovery + text sniffing
# (source_file_refs, is_text_source) are imported from common above, shared with
# coverage.py.


def unconverted_binary_sources(root: Path) -> list[str]:
    """List binary files under sources/ that have no runs/sources/ conversion.

    A binary original in sources/ yields no facts on its own, but if
    `factlog ingest` has produced a runs/sources/<stem>.{md,txt} conversion the
    text IS ingested, so such originals are NOT reported. Hidden/system files
    (names starting with '.', e.g. .DS_Store) are skipped to avoid noise.
    Sources on the sync-ignore list (policy/sync-ignore.md) are skipped too:
    they are excluded from sync on purpose, so a missing conversion is expected.
    """
    base = root / "sources"
    derived = root / "runs" / "sources"
    if not base.is_dir():
        return []
    patterns = sync_ignore_patterns(root)
    found: list[str] = []
    for path in sorted(p for p in base.rglob("*") if p.is_file()):
        if path.name.startswith("."):
            continue
        if is_text_source(path):
            continue
        # ingest mirrors the original's subdirectory, so look for the conversion
        # at runs/sources/<same-subdir>/<stem>.{md,txt}, not a flat name.
        rel_parent = path.relative_to(base).parent
        if any((derived / rel_parent / f"{path.stem}{ext}").is_file() for ext in (".md", ".txt")):
            continue
        ref = unicodedata.normalize("NFC", path.relative_to(root).as_posix())
        if is_sync_ignored(ref, patterns):
            continue
        found.append(path.relative_to(root).as_posix())
    return found


# ---------------------------------------------------------------------------
# Input: read candidate rows from runs/*.json
# ---------------------------------------------------------------------------

def load_candidate_files(root: Path, pattern: str = "runs/*.json") -> list[dict[str, str]]:
    """Read all JSON files matching *pattern* under *root*.

    Each file must contain a JSON array of objects with FACT_HEADER keys.
    Invalid rows are skipped with a warning; invalid files raise SystemExit.

    The "source" field in each row must be a sources/-prefixed path relative to
    the KB root (e.g. "sources/my-doc.md").  Bare filenames are NOT accepted.
    """
    rows: list[dict[str, str]] = []
    candidate_files = sorted(root.glob(pattern))
    if not candidate_files:
        # No candidates yet — not an error; we will just write an empty CSV.
        return rows

    for path in candidate_files:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            raise SystemExit(f"failed to parse {path.relative_to(root)}: {exc}") from exc
        if not isinstance(data, list):
            # Not a candidate-rows file (a fact run is a JSON array). Other tools
            # also write JSON under runs/ — e.g. generate_logic_policy.py writes
            # runs/natural-language-to-policy-response.json (an object). Skip such
            # non-array files with a warning instead of failing, so the pipeline
            # stays idempotent when those artifacts are present.
            print(
                f"  skip non-candidate JSON in {path.parent.name}/: {path.name} (not a JSON array)",
                file=sys.stderr,
            )
            continue
        for item in data:
            if not isinstance(item, dict):
                continue
            row = {field: str(item.get(field, "")).strip() for field in FACT_HEADER}
            if all(row[field] for field in FACT_HEADER[:4]):
                rows.append(row)
            else:
                print(
                    f"  skip incomplete row in {path.name}: {item}",
                    file=sys.stderr,
                )
    return rows


# ---------------------------------------------------------------------------
# Normalise & dedup
# ---------------------------------------------------------------------------

def normalize_rows(
    root: Path,
    rows: list[dict[str, str]],
    *,
    strict: bool = False,
) -> list[dict[str, str]]:
    """Validate, normalise, and deduplicate raw candidate rows.

    The "source" field must be a sources/-prefixed path relative to the KB root
    (e.g. "sources/my-doc.md" or "sources/subdir/notes.md#anchor").  A bare
    filename ("my-doc.md") does not match and the row is dropped.

    - status is normalised to 'needs_review' if not in VALID_STATUSES
    - confidence is clamped to [0.00, 1.00]
    - duplicate (subject, relation, object, source-file) tuples collapse to one
      row.  The dedup key strips any '#anchor' (so 'sources/a.md' and
      'sources/a.md#sec1' are one fact), consistent with the anchor-insensitive
      status-preservation keys (existing_superseded_keys / existing_engine_keys
      / existing_review_keys).  The surviving row is chosen deterministically:
      the one whose full 'source' sorts lexicographically first — a bare
      'sources/a.md' (a prefix of, thus less than, any 'sources/a.md#anchor')
      wins over every anchored variant, otherwise the lexicographically-first
      anchor wins.  This is independent of input row order.
    - result is sorted by (source, subject, relation, object)

    If *strict* is True, any dropped row causes a non-zero exit.
    """
    known_sources = source_file_refs(root)
    # Anchor-insensitive dedup: key on (subject, relation, object, source-file),
    # mapping to the surviving row.  On collision the row whose full 'source'
    # sorts lexicographically first wins (bare path < anchored variant), so the
    # winner is fixed by value, not input order.
    dedup: dict[tuple[str, str, str, str], dict[str, str]] = {}
    dropped = 0

    for row in rows:
        # NFC-normalise the source: macOS stores filenames as NFD, but extracted
        # sources are typically NFC; comparing/storing NFC keeps both sides equal
        # so a Korean-named source's facts are not silently dropped (and the
        # canonical value written to candidates.csv is consistently NFC).
        source = unicodedata.normalize("NFC", row["source"])
        # Compare the pre-anchor portion against known sources/-prefixed refs.
        # The canonical source value is already sources/-prefixed; bare filenames
        # will not match and are dropped with a warning.
        source_file = source.partition("#")[0]
        if source_file not in known_sources:
            print(
                f"  skip row: source '{source_file}' not found in sources/ "
                f"(expected a sources/- or runs/sources/-prefixed path like 'sources/{Path(source_file).name}')",
                file=sys.stderr,
            )
            dropped += 1
            if strict:
                raise SystemExit(
                    f"--strict: input row rejected (source not found): {source_file}"
                )
            continue
        clean = {field: row.get(field, "").strip() for field in FACT_HEADER}
        clean["source"] = source  # NFC-normalised canonical source
        clean["status"] = clean["status"] if clean["status"] in VALID_STATUSES else "needs_review"
        clean["confidence"] = normalize_confidence(clean["confidence"])
        # Canonicalise an `amount(N,"unit")` object to the quote-free `amount(N,unit)`
        # form: the engine .dl text parser rejects escaped quotes, so a quoted unit
        # would break facts/accepted.dl as a whole-program ParseError (#154). Done
        # before the dedup key so `amount(7,"억")` and `amount(7,억)` collapse to one.
        canon_amount = literal_types.canonical_amount(clean["object"])
        if canon_amount is not None:
            clean["object"] = canon_amount
        # Anchor-insensitive key: source_file is the pre-'#anchor' portion
        # (already computed above for the source-existence check).
        key = (clean["subject"], clean["relation"], clean["object"], source_file)
        existing = dedup.get(key)
        if existing is None:
            dedup[key] = clean
        else:
            dropped += 1
            # Keep the row whose full source sorts first (bare < anchored).
            if clean["source"] < existing["source"]:
                dedup[key] = clean

    if dropped:
        print(f"  warning: {dropped} row(s) dropped during normalise/dedup", file=sys.stderr)

    return sorted(
        dedup.values(),
        key=lambda item: (item["source"], item["subject"], item["relation"], item["object"]),
    )


# ---------------------------------------------------------------------------
# Write facts/candidates.csv
# ---------------------------------------------------------------------------

def write_facts(root: Path, rows: list[dict[str, str]]) -> None:
    out = root / "facts" / "candidates.csv"
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FACT_HEADER)
        writer.writeheader()
        writer.writerows(rows)


# ---------------------------------------------------------------------------
# Write pages/<entity>.md
# ---------------------------------------------------------------------------

def page_filename(title: str) -> str:
    return f"{slugify(title)}.md"


def load_page_template(root: Path) -> str:
    """Return the concept-page template: <kb>/templates/pages.md if present,
    else the built-in DEFAULT_PAGE_TEMPLATE (backward-compatible).

    CRLF is normalised to LF. An empty/whitespace-only custom template falls back
    to the default (with a warning); a non-empty one with no recognised
    placeholder is honoured but warned about (pages would be static text)."""
    custom = root / PAGE_TEMPLATE_REL
    if not custom.is_file():
        return DEFAULT_PAGE_TEMPLATE
    text = custom.read_text(encoding="utf-8").replace("\r\n", "\n")
    if not text.strip():
        print(f"  {PAGE_TEMPLATE_REL} is empty; using built-in default page template", file=sys.stderr)
        return DEFAULT_PAGE_TEMPLATE
    if not _PAGE_PLACEHOLDER_RE.search(text):
        print(
            f"  {PAGE_TEMPLATE_REL} has no {{{{ENTITY}}}}/{{{{SOURCES}}}}/{{{{RELATIONS}}}}/{{{{REVIEW}}}}"
            " placeholders; generated pages will be static text",
            file=sys.stderr,
        )
    return text


def render_page(template: str, entity: str, sources: str, relations: str, review: str) -> str:
    """Substitute the page placeholders and guarantee the generated marker.

    Substitution is a SINGLE regex pass: each {{...}} is replaced exactly once,
    so a value placed in one slot (e.g. a source string that literally contains
    '{{REVIEW}}') is never re-scanned and re-substituted. The marker is what
    makes regeneration non-destructive (hand-authored pages are never
    overwritten); if a custom template doesn't start with it, prepend it so a
    user's edit cannot silently break regeneration detection."""
    mapping = {"ENTITY": entity, "SOURCES": sources, "RELATIONS": relations, "REVIEW": review}
    text = _PAGE_PLACEHOLDER_RE.sub(lambda m: mapping[m.group(1)], template)
    if not text.startswith(GENERATED_PAGE_MARKER):
        text = f"{GENERATED_PAGE_MARKER}\n{text}"
    return text


def write_pages(root: Path, rows: list[dict[str, str]]) -> list[str]:
    """Generate per-entity concept pages from confirmed/accepted candidate rows.

    Only pages carrying GENERATED_PAGE_MARKER are touched; hand-authored pages
    are never overwritten.  Pre-existing pages generated by earlier tooling
    that carry a different marker are NOT reclaimed — they remain as-is and
    are excluded from this script's management scope.
    """
    pages_dir = root / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)
    template = load_page_template(root)

    # Remove previously generated pages (ours only).
    for page in pages_dir.glob("*.md"):
        text = page.read_text(encoding="utf-8", errors="ignore")
        if GENERATED_PAGE_MARKER in text:
            page.unlink()

    # Superseded rows are retired: keep them in candidates.csv (audit) but do not
    # render them on concept pages, where they would read as the current value.
    rows = [row for row in rows if row.get("status") not in SUPERSEDED_STATUSES]

    by_entity: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        by_entity.setdefault(row["subject"], []).append(row)
        by_entity.setdefault(row["object"], []).append(row)

    written: list[str] = []
    for entity, entity_rows in sorted(by_entity.items()):
        if not entity.strip():
            continue
        path = pages_dir / page_filename(entity)
        # Skip hand-authored pages that don't carry our marker.
        if path.exists() and GENERATED_PAGE_MARKER not in path.read_text(encoding="utf-8", errors="ignore"):
            continue

        source_lines = sorted({f"- {row['source']}" for row in entity_rows})
        relation_lines: list[str] = []
        review_lines: list[str] = []

        for row in entity_rows:
            if row["subject"] == entity:
                relation_lines.append(
                    f"- {row['relation']} -> [[{row['object']}]]"
                    f" ({row['source']}, confidence={row['confidence']})"
                )
            else:
                relation_lines.append(
                    f"- [[{row['subject']}]] -> {row['relation']}"
                    f" ({row['source']}, confidence={row['confidence']})"
                )
            if row["status"] in REVIEW_STATUSES:
                review_lines.append(
                    f"- {row['subject']} / {row['relation']} / {row['object']}"
                    f" (confidence={row['confidence']}): {row['note']}"
                )

        text = render_page(
            template,
            entity,
            "\n".join(source_lines or ["- 확인된 source가 없습니다."]),
            "\n".join(relation_lines or ["- 확인된 관계가 없습니다."]),
            "\n".join(review_lines or ["- 현재 추출 결과에서 별도 검토 항목이 없습니다."]),
        )
        path.write_text(text, encoding="utf-8")
        written.append(path.relative_to(root).as_posix())

    return written


# ---------------------------------------------------------------------------
# Write decisions/open-questions.md
# ---------------------------------------------------------------------------

def decision_section(row: dict[str, str]) -> str:
    text = " ".join(row.get(key, "") for key in ["subject", "relation", "object", "note"]).lower()
    if any(word in text for word in ["duplicate", "same_concept", "same_as", "동일", "중복"]):
        return "## 중복 개념 후보"
    if any(word in text for word in ["source", "evidence", "출처"]):
        return "## 출처 부족"
    if any(word in text for word in ["conflict", "충돌"]):
        return "## 기존 내용과 충돌할 수 있는 항목"
    return "## 모호한 관계명"


def insert_bullet(text: str, section: str, bullet: str) -> str:
    lines = text.splitlines()
    # Idempotency by exact line, not substring: a plain `bullet in text` dropped a
    # new bullet whenever it was a prefix-substring of a longer existing bullet
    # (e.g. "...note" skipped because "...note extra" was already present).
    if bullet.rstrip() in {line.rstrip() for line in lines}:
        return text
    try:
        index = lines.index(section)
    except ValueError:
        if text and not text.endswith("\n"):
            text += "\n"
        return f"{text}\n{section}\n{bullet}\n"

    insert_at = index + 1
    while insert_at < len(lines) and not lines[insert_at].startswith("## "):
        insert_at += 1
    if insert_at > index + 1 and lines[insert_at - 1].strip():
        lines.insert(insert_at, "")
        insert_at += 1
    lines.insert(insert_at, bullet)
    return "\n".join(lines).rstrip() + "\n"


def write_decisions(root: Path, rows: list[dict[str, str]]) -> list[str]:
    decisions = root / "decisions" / "open-questions.md"
    decisions.parent.mkdir(parents=True, exist_ok=True)
    text = decisions.read_text(encoding="utf-8") if decisions.exists() else "# Open Questions\n"
    added: list[str] = []
    for row in rows:
        if row["status"] not in REVIEW_STATUSES:
            continue
        bullet = (
            f"- needs_review: {row['subject']} / {row['relation']} / "
            f"{row['object']} ({row['source']}, confidence={row['confidence']}) - {row['note']}"
        )
        before = text
        text = insert_bullet(text, decision_section(row), bullet)
        if text != before:
            added.append(bullet)
    decisions.write_text(text, encoding="utf-8")
    return added


# ---------------------------------------------------------------------------
# Record stale page references
# ---------------------------------------------------------------------------

def existing_source_refs(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    # Match the ingestible text extensions a page can cite (md/txt/csv — pdftotext
    # and textutil emit .txt, direct text sources may be .txt/.csv), with the
    # optional runs/ prefix, for parity with validate.py. An .md-only pattern
    # silently never recorded stale refs to deleted .txt/.csv sources.
    return re.findall(r"(?:runs/)?sources/[^\s`)>,]+?\.(?:md|txt|csv)(?:#[^\s`)>,]+)?", text)


def record_stale_page_refs(root: Path) -> list[str]:
    known_sources = source_file_refs(root)
    decisions = root / "decisions" / "open-questions.md"
    text = decisions.read_text(encoding="utf-8") if decisions.exists() else "# Open Questions\n"
    added: list[str] = []
    for page in sorted((root / "pages").glob("*.md")):
        for ref in existing_source_refs(page):
            source_file = unicodedata.normalize("NFC", ref.partition("#")[0])
            if source_file in known_sources:
                continue
            bullet = f"- stale_source: {page.relative_to(root).as_posix()} references removed source {ref}"
            before = text
            text = insert_bullet(text, "## 출처 부족", bullet)
            if text != before:
                added.append(bullet)
    decisions.write_text(text, encoding="utf-8")
    return added


# ---------------------------------------------------------------------------
# Validation delegate — repoints to tools/validate.py (u5)
# ---------------------------------------------------------------------------

def validate_outputs(root: Path) -> int:
    """Delegate structural validation to tools/validate.py.

    This replaces the old run_fact_sync.py reference to validate_fact_sync.py.
    """
    validator = Path(__file__).parent / "validate.py"
    if not validator.is_file():
        print(f"warning: validate.py not found at {validator}", file=sys.stderr)
        return 0
    completed = subprocess.run(
        [sys.executable, str(validator), str(root)],
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.stdout.strip():
        print(completed.stdout.strip())
    if completed.stderr.strip():
        print(completed.stderr.strip(), file=sys.stderr)
    return completed.returncode


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def existing_superseded_keys(root: Path) -> set[tuple[str, str, str, str]]:
    """(subject, relation, object, source) of rows currently marked 'superseded'
    in candidates.csv. Preserved across re-merge so a human's conflict resolution
    (or `factlog eject --fact`) sticks even when a run re-asserts the retired fact.

    The source is keyed WITHOUT its '#anchor' (partitioned on '#', same as
    normalize_rows' source-existence check), so a supersession survives a later
    sync that re-asserts the same triple from the same file with a drifted
    section anchor (sources/a.md#sec3 -> sources/a.md). Different files stay
    distinct, so a supersession is still scoped to the source file it came from."""
    csv_path = root / "facts" / "candidates.csv"
    if not csv_path.is_file():
        return set()
    keys: set[tuple[str, str, str, str]] = set()
    with csv_path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if (row.get("status") or "").strip() in SUPERSEDED_STATUSES:
                keys.add(
                    (
                        (row.get("subject") or "").strip(),
                        (row.get("relation") or "").strip(),
                        (row.get("object") or "").strip(),
                        (row.get("source") or "").strip().partition("#")[0],
                    )
                )
    return keys


def existing_engine_keys(root: Path) -> dict[tuple[str, str, str, str], str]:
    """Map (subject, relation, object, source-without-#anchor) -> engine status
    for rows currently marked confirmed/accepted in candidates.csv.

    Preserved across re-merge so a human acceptance (`factlog accept` /
    `amend --accept`, or a hand-confirm) sticks even though extraction re-asserts
    the fact as `candidate` — symmetric with existing_superseded_keys. The exact
    engine status (confirmed vs accepted) is kept. Anchor-insensitive key, like
    the superseded preservation."""
    csv_path = root / "facts" / "candidates.csv"
    if not csv_path.is_file():
        return {}
    keys: dict[tuple[str, str, str, str], str] = {}
    with csv_path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            status = (row.get("status") or "").strip()
            if status in ENGINE_STATUSES:
                key = (
                    (row.get("subject") or "").strip(),
                    (row.get("relation") or "").strip(),
                    (row.get("object") or "").strip(),
                    (row.get("source") or "").strip().partition("#")[0],
                )
                keys[key] = status
    return keys


def existing_review_keys(root: Path) -> set[tuple[str, str, str, str]]:
    """Keys (subject, relation, object, source-without-#anchor) a human pulled back
    to `needs_review` in the live candidates.csv.

    Preserved across re-merge so a deliberate re-review survives: a stale
    runs/*.json value left from an earlier accept (status 'accepted') must not
    silently re-promote a fact the human downgraded. Only `needs_review` is held
    (not the default `candidate`), and superseded is stronger and still wins.
    Anchor-insensitive key, like existing_engine_keys / existing_superseded_keys."""
    csv_path = root / "facts" / "candidates.csv"
    if not csv_path.is_file():
        return set()
    keys: set[tuple[str, str, str, str]] = set()
    with csv_path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if (row.get("status") or "").strip() == "needs_review":
                keys.add((
                    (row.get("subject") or "").strip(),
                    (row.get("relation") or "").strip(),
                    (row.get("object") or "").strip(),
                    (row.get("source") or "").strip().partition("#")[0],
                ))
    return keys


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Merge Claude-extracted candidate rows (runs/*.json) into the factlog KB.\n"
            "\n"
            "Input: JSON files under $FACTLOG_ROOT/runs/ produced by the native\n"
            "Claude fact-extraction step in the factlog skill.  Each file must\n"
            "contain a JSON array of objects with the FACT_HEADER schema:\n"
            "  [subject, relation, object, source, status, confidence, note]\n"
            "\n"
            "The 'source' field MUST be a sources/- or runs/sources/-prefixed path relative to the KB\n"
            "root (e.g. 'sources/my-doc.md').  Bare filenames are not accepted.\n"
            "\n"
            "Output: facts/candidates.csv, pages/, decisions/open-questions.md"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--wiki",
        default=os.environ.get("FACTLOG_ROOT", "."),
        help="KB root (authoritative; sets FACTLOG_ROOT; default: $FACTLOG_ROOT or '.')",
    )
    parser.add_argument(
        "--input",
        default=None,
        help=(
            "glob pattern relative to KB root for input JSON files "
            "(default: runs/*.json via common.RUNS_DIR)"
        ),
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="exit non-zero if any input row is rejected during normalisation",
    )
    args = parser.parse_args()

    root = Path(args.wiki).expanduser().resolve()

    # Derive the default --input glob from common.RUNS_DIR so the runs/ location
    # is single-sourced from common.py.
    if args.input is not None:
        input_pattern = args.input
    else:
        try:
            input_pattern = f"{RUNS_DIR.relative_to(root)}/*.json"
        except ValueError:
            input_pattern = "runs/*.json"

    # Validate KB structure and ensure output directories exist.
    ensure_dirs()

    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    print(f"merge_candidates run_id={run_id} wiki={root}")

    # ------------------------------------------------------------------
    # 0. Surface binary source files in sources/ that have NO runs/sources/
    # conversion. Extraction reads sources/ as text, so an un-ingested binary
    # yields no facts (silent non-ingestion). Warn always; under --strict treat
    # their presence as a hard failure.
    # ------------------------------------------------------------------
    nontext_sources = unconverted_binary_sources(root)
    if nontext_sources:
        print(
            f"  WARNING: {len(nontext_sources)} binary source file(s) in sources/ "
            "have no runs/sources/ conversion and will yield no facts "
            "(run `factlog ingest --scan` to convert them):",
            file=sys.stderr,
        )
        for name in nontext_sources:
            print(f"    - {name}", file=sys.stderr)

    # ------------------------------------------------------------------
    # 1. Read candidate rows from runs/*.json
    # ------------------------------------------------------------------
    raw_rows = load_candidate_files(root, input_pattern)
    print(f"  candidate rows loaded: {len(raw_rows)}")

    # ------------------------------------------------------------------
    # 2. Normalise and deduplicate
    # ------------------------------------------------------------------
    rows = normalize_rows(root, raw_rows, strict=args.strict)
    print(f"  rows after normalise/dedup: {len(rows)}")

    # Preserve human-marked supersessions across re-merge: a row previously set
    # to 'superseded' in candidates.csv stays superseded even if a run re-asserts
    # it — so a conflict resolution (see check_conflicts.py) is durable.
    superseded_keys = existing_superseded_keys(root)
    if superseded_keys:
        preserved = 0
        for row in rows:
            # Anchor-insensitive key (see existing_superseded_keys): a drifted
            # section anchor must not let a retired fact slip back in.
            key = (row["subject"], row["relation"], row["object"], row["source"].partition("#")[0])
            if key in superseded_keys and row["status"] not in SUPERSEDED_STATUSES:
                row["status"] = "superseded"
                preserved += 1
        if preserved:
            print(f"  preserved {preserved} superseded row(s) from candidates.csv")

    # Preserve human acceptances across re-merge: a row a human set to
    # confirmed/accepted stays so even though extraction re-asserts it as
    # 'candidate' — symmetric with the superseded preservation above. Skip rows
    # now superseded (a later rejection wins over an earlier acceptance).
    engine_keys = existing_engine_keys(root)
    if engine_keys:
        restored = 0
        for row in rows:
            key = (row["subject"], row["relation"], row["object"], row["source"].partition("#")[0])
            want = engine_keys.get(key)
            if want and row["status"] not in SUPERSEDED_STATUSES and row["status"] != want:
                row["status"] = want
                restored += 1
        if restored:
            print(f"  preserved {restored} human-accepted row(s) from candidates.csv")

    # Respect a deliberate human re-review: a row the human pulled back to
    # needs_review in candidates.csv must not be silently re-promoted by a stale
    # engine status carried in runs/*.json (e.g. left from an earlier accept).
    # Only engine statuses are overridden — a re-asserted 'candidate' is untouched
    # — and superseded (handled above) still wins.
    review_keys = existing_review_keys(root)
    if review_keys:
        held = 0
        for row in rows:
            key = (row["subject"], row["relation"], row["object"], row["source"].partition("#")[0])
            if key in review_keys and row["status"] in ENGINE_STATUSES:
                row["status"] = "needs_review"
                held += 1
        if held:
            print(f"  held {held} human-reviewed row(s) at needs_review (re-review respected)")

    # Warn prominently when rows were loaded but all were dropped — this
    # distinguishes a silent contract violation from a genuinely empty run.
    if raw_rows and not rows:
        print(
            "  WARNING: all candidate rows were dropped during normalise/dedup "
            "(0 rows survived).  Check that source values are sources/- or runs/sources/-prefixed paths.",
            file=sys.stderr,
        )
        if args.strict:
            return 1

    # ------------------------------------------------------------------
    # 3. Write facts/candidates.csv
    # ------------------------------------------------------------------
    write_facts(root, rows)
    print(f"  facts/candidates.csv written ({len(rows)} rows)")

    # ------------------------------------------------------------------
    # 4. Record stale page references (before pages are re-generated)
    # ------------------------------------------------------------------
    stale_refs_added = record_stale_page_refs(root)
    print(f"  stale page refs recorded: {len(stale_refs_added)}")

    # ------------------------------------------------------------------
    # 5. Write pages/<entity>.md
    # ------------------------------------------------------------------
    pages_written = write_pages(root, rows)
    print(f"  pages written: {len(pages_written)}")

    # ------------------------------------------------------------------
    # 6. Write decisions/open-questions.md bullets for needs_review rows
    # ------------------------------------------------------------------
    decisions_added = write_decisions(root, rows)
    print(f"  decision bullets added: {len(decisions_added)}")

    # ------------------------------------------------------------------
    # 7. Delegate structural validation to tools/validate.py
    # Validation is informational: merge_candidates exits 0 on success
    # regardless of validation result.  Callers that need strict validation
    # should run tools/validate.py directly.
    # ------------------------------------------------------------------
    validation_code = validate_outputs(root)
    if validation_code != 0:
        print(f"  validation warnings (exit {validation_code}) — run validate.py for details", file=sys.stderr)

    if args.strict and nontext_sources:
        print(
            f"--strict: {len(nontext_sources)} unconverted binary source file(s) in sources/",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    from common import run_cli

    sys.exit(run_cli(main))
